services:
  - type: web
    name: codealo-commerce-api
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: rsync -a public/ /data/public/ && yarn start
    healthCheckPath: /_health
    disk:
      name: codealo-commerce-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 14.18.2
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILENAME
        value: /data/codealo-commerce-api.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true